mysql:
  source: # 主数据库
    driverName:   mysql
    host:         127.0.0.1
    port:         3306
    database:     profstik
    username:     root
    password:     123456
    charset:      utf8mb4

  replica1: # 从数据库
    driverName: mysql
    host: 127.0.0.1
    port: 3310
    database: db_tiktok
    username: tiktokDB
    password: tiktokDB
    charset: utf8mb4
  replica2: # 从数据库
    driverName: mysql
    host: 127.0.0.1
    port: 3308
    database: db_tiktok
    username: tiktokDB
    password: tiktokDB
    charset: utf8mb4



config:
  MaxOpenCons:     1000
  MaxIdleCons:     20
  ConnMaxLifetime: 60 * time.Minute